### ISSUE TITLE
Plugin throws Exception

### ISSUE THREAD

**Issue by JulianGerhard** [shyim/LightweightModule#1]
If unpacked and installed, Plugin throws Exception:

`Unable to install, got exception: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.onclick AS onclick_3, t0.class AS class_4, t0.position AS position_5, t0.active AS active_6, t0.pluginID AS pluginID_7, t0.controller AS controller_8, t0.action AS action_9, t0.shortcut AS shortcut_10, t0.parent AS parent_11, t0.parent AS parent_12, t0.pluginID AS pluginID_13 FROM s_core_menu t0 ORDER BY LIMIT 1': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 1' at line 1`

Shopware: 5.2.8
No other Plugins installed.

**Comment by shyim** [comment]
Fixed with Commit https://github.com/shyim/LightweightModule/commit/4e8884d2add74f614ee9f5ef924454cba45875f1
